version: "3"

tasks:
  setup:
    desc: Install frontend and backend dependencies + generate SSL cert
    cmds:
      - task: generate:cert
      - task: install:client
      - task: install:server

  install:client:
    desc: npm install inside ClientApp/
    dir: ClientApp
    cmds:
      - npm install

  install:server:
    desc: dotnet restore inside WebApi/
    dir: WebApi
    cmds:
      - dotnet restore

  generate:cert:
    desc: Generate localhost SSL certificate
    dir: ClientApp/ssl
    status:
      - test -f localhost.crt
      - test -f localhost.key
    cmds:
      - openssl req -x509 -newkey rsa:2048 -keyout localhost.key -out localhost.crt -days 365 -nodes -subj "/CN=localhost"

  frontend:
    desc: Run Angular frontend (watch mode)
    dir: ClientApp
    cmds:
      - npm run start

  backend:
    desc: Run .NET backend (watch mode)
    dir: WebApi
    cmds:
      - dotnet watch run

  dev:
    desc: Run frontend and backend concurrently
    cmds:
      - task -p backend frontend
