/**
 * WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FieldName = 'email' | 'password' | 'displayName' | 'general';

export const FieldName = {

    Email: 'email' as FieldName,

    Password: 'password' as FieldName,

    DisplayName: 'displayName' as FieldName,

    General: 'general' as FieldName
};

