/**
 * WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldName } from './fieldName';


export interface FieldError { 
    field: FieldName;
    message: string;
}
export namespace FieldError {
}


