/**
 * WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FieldName = 'Email' | 'Password' | 'DisplayName' | 'General';

export const FieldName = {

    Email: 'Email' as FieldName,

    Password: 'Password' as FieldName,

    DisplayName: 'DisplayName' as FieldName,

    General: 'General' as FieldName
};

