/**
 * WebAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldError } from './fieldError';
import { AuthStatusResponse } from './authStatusResponse';


export interface OperationResultOfAuthStatusResponse { 
    success?: boolean;
    data?: AuthStatusResponse | null;
    message?: string;
    errors?: Array<FieldError> | null;
    errorCode?: string | null;
}

